services:
  - type: web
    name: taung-thu-fastapi
    runtime: python
    plan: free
    buildCommand: pip install -r ml/requirements.txt
    startCommand: python -m uvicorn ml.api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
