-- 1. Enable needed extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Base Configuration Tables (Seed Data)
CREATE TABLE regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id)
);

CREATE TABLE markets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL,
  region_id BIGINT REFERENCES regions(id)
);

-- 3. Profiles (Mapping to Supabase auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('farmer', 'merchant', 'admin')),
  region_id BIGINT REFERENCES regions(id),
  trust_level TEXT DEFAULT 'standard', -- standard, verified, flagged, suspended
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create a trigger to auto-create profile on signup (Optional if you already handle it in API/Frontend)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'role');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. Farmer Data
CREATE TABLE farmer_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  harvest_qty NUMERIC,
  storage_qty NUMERIC,
  sale_date DATE,
  sale_price NUMERIC,
  total_amount NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Merchant Data (Prices)
CREATE TABLE price_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  market_id BIGINT REFERENCES markets(id),
  buy_price NUMERIC NOT NULL,
  sell_price NUMERIC NOT NULL,
  quality TEXT DEFAULT 'standard',
  unit TEXT DEFAULT 'basket',
  frequency TEXT DEFAULT 'daily',
  status TEXT DEFAULT 'pending', -- pending, peer_verified, admin_verified, flagged, rejected
  comparison_label TEXT DEFAULT 'moderate', -- higher, lower, moderate (set by AI/Admin logic)
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE peer_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_submission_id BIGINT REFERENCES price_submissions(id) ON DELETE CASCADE,
  verifier_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  is_verified BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Merchant Data (Listings / Trade Offers)
CREATE TABLE listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  region_id BIGINT REFERENCES regions(id),
  type TEXT CHECK (type IN ('buy', 'sell')),
  quantity NUMERIC NOT NULL,
  target_price NUMERIC NOT NULL,
  availability TEXT DEFAULT 'immediate',
  pickup_available BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'active', -- active, paused, closed
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Admin & Platform Data
CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE emergencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  region_id BIGINT REFERENCES regions(id),
  risk_level TEXT DEFAULT 'medium', -- low, medium, high
  affected_farmers INT DEFAULT 0,
  affected_merchants INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'general',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- SEED DUMMY DATA (Optional but highly recommended to make UI dropdowns work)
-- -----------------------------------------------------------------------------

INSERT INTO regions (id, name_mm) VALUES 
  (1, 'မန္တလေးတိုင်း'), 
  (2, 'စစ်ကိုင်းတိုင်း'), 
  (3, 'မကွေးတိုင်း'), 
  (4, 'ရှမ်းပြည်နယ်'), 
  (5, 'ရန်ကုန်တိုင်း') ON CONFLICT DO NOTHING;

INSERT INTO categories (id, name_mm) VALUES 
  (1, 'ဆီထွက်သီးနှံ'), 
  (2, 'စပါး'), 
  (3, 'ပဲအမျိုးမျိုး') ON CONFLICT DO NOTHING;

INSERT INTO products (id, name_mm, category_id) VALUES 
  (1, 'နှမ်း (Sesame)', 1), 
  (2, 'မြေပဲ (Groundnut)', 1), 
  (3, 'နေကြာ (Sunflower)', 1),
  (4, 'မတ်ပဲ (Black Gram)', 3),
  (5, 'ရွှေဘိုပေါ်ဆန်း', 2) ON CONFLICT DO NOTHING;

INSERT INTO markets (id, name_mm, region_id) VALUES 
  (1, 'မန္တလေးပွဲရုံ', 1), 
  (2, 'မိတ္ထီလာပွဲရုံ', 1), 
  (3, 'မကွေးကုန်စည်ဒိုင်', 3), 
  (4, 'အောင်ပန်းစျေး', 4) ON CONFLICT DO NOTHING;

-- Reset sequence for standard auto-increment
SELECT setval('regions_id_seq', (SELECT MAX(id) FROM regions));
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
SELECT setval('markets_id_seq', (SELECT MAX(id) FROM markets));
