-- -----------------------------------------------------------------------------
-- Taung Thu App - Supabase Schema
-- Safe for fresh project setup with auth trigger, RLS, starter policies, and seed data
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Base tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  UNIQUE (name_mm, category_id)
);

CREATE TABLE IF NOT EXISTS public.markets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mm TEXT NOT NULL,
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  UNIQUE (name_mm, region_id)
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  role TEXT NOT NULL DEFAULT 'farmer' CHECK (role IN ('farmer', 'merchant', 'admin')),
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  trust_level TEXT NOT NULL DEFAULT 'standard'
    CHECK (trust_level IN ('standard', 'verified', 'flagged', 'suspended')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.farmer_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  harvest_qty NUMERIC,
  storage_qty NUMERIC,
  sale_date DATE,
  sale_price NUMERIC,
  total_amount NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.price_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  market_id BIGINT REFERENCES public.markets(id) ON DELETE SET NULL,
  buy_price NUMERIC NOT NULL,
  sell_price NUMERIC NOT NULL,
  quality TEXT NOT NULL DEFAULT 'standard',
  unit TEXT NOT NULL DEFAULT 'basket',
  frequency TEXT NOT NULL DEFAULT 'daily',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'peer_verified', 'admin_verified', 'flagged', 'rejected')),
  comparison_label TEXT NOT NULL DEFAULT 'moderate'
    CHECK (comparison_label IN ('higher', 'lower', 'moderate')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.peer_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_submission_id BIGINT NOT NULL REFERENCES public.price_submissions(id) ON DELETE CASCADE,
  verifier_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_verified BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (price_submission_id, verifier_id)
);

CREATE TABLE IF NOT EXISTS public.listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('buy', 'sell')),
  quantity NUMERIC NOT NULL,
  target_price NUMERIC NOT NULL,
  availability TEXT NOT NULL DEFAULT 'immediate',
  pickup_available BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'paused', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.emergencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  risk_level TEXT NOT NULL DEFAULT 'medium'
    CHECK (risk_level IN ('low', 'medium', 'high')),
  affected_farmers INT NOT NULL DEFAULT 0,
  affected_merchants INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'general',
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Helper functions and triggers
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requested_role TEXT;
BEGIN
  requested_role := COALESCE(new.raw_user_meta_data ->> 'role', 'farmer');

  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data ->> 'full_name', ''),
    CASE
      WHEN requested_role IN ('farmer', 'merchant', 'admin') THEN requested_role
      ELSE 'farmer'
    END
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN new;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_admin(check_user UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = check_user
      AND role = 'admin'
      AND is_active = true
  );
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DROP TRIGGER IF EXISTS set_price_submissions_updated_at ON public.price_submissions;
CREATE TRIGGER set_price_submissions_updated_at
  BEFORE UPDATE ON public.price_submissions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_listings_updated_at ON public.listings;
CREATE TRIGGER set_listings_updated_at
  BEFORE UPDATE ON public.listings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Helpful indexes
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_region_id ON public.profiles(region_id);
CREATE INDEX IF NOT EXISTS idx_farmer_records_farmer_id ON public.farmer_records(farmer_id);
CREATE INDEX IF NOT EXISTS idx_farmer_records_product_id ON public.farmer_records(product_id);
CREATE INDEX IF NOT EXISTS idx_price_submissions_merchant_id ON public.price_submissions(merchant_id);
CREATE INDEX IF NOT EXISTS idx_price_submissions_market_id ON public.price_submissions(market_id);
CREATE INDEX IF NOT EXISTS idx_price_submissions_status ON public.price_submissions(status);
CREATE INDEX IF NOT EXISTS idx_peer_verifications_submission_id ON public.peer_verifications(price_submission_id);
CREATE INDEX IF NOT EXISTS idx_listings_merchant_id ON public.listings(merchant_id);
CREATE INDEX IF NOT EXISTS idx_listings_region_id ON public.listings(region_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farmer_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peer_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Public read for reference data
DROP POLICY IF EXISTS "regions are readable by authenticated users" ON public.regions;
CREATE POLICY "regions are readable by authenticated users"
  ON public.regions
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "categories are readable by authenticated users" ON public.categories;
CREATE POLICY "categories are readable by authenticated users"
  ON public.categories
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "products are readable by authenticated users" ON public.products;
CREATE POLICY "products are readable by authenticated users"
  ON public.products
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "markets are readable by authenticated users" ON public.markets;
CREATE POLICY "markets are readable by authenticated users"
  ON public.markets
  FOR SELECT
  TO authenticated
  USING (true);

-- Profiles
DROP POLICY IF EXISTS "users can read own profile" ON public.profiles;
CREATE POLICY "users can read own profile"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "users can update own profile" ON public.profiles;
CREATE POLICY "users can update own profile"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id OR public.is_admin())
  WITH CHECK (auth.uid() = id OR public.is_admin());

-- Farmer records
DROP POLICY IF EXISTS "farmers can manage own records" ON public.farmer_records;
CREATE POLICY "farmers can manage own records"
  ON public.farmer_records
  FOR ALL
  TO authenticated
  USING (farmer_id = auth.uid() OR public.is_admin())
  WITH CHECK (farmer_id = auth.uid() OR public.is_admin());

-- Price submissions
DROP POLICY IF EXISTS "authenticated users can read approved prices" ON public.price_submissions;
CREATE POLICY "authenticated users can read approved prices"
  ON public.price_submissions
  FOR SELECT
  TO authenticated
  USING (
    merchant_id = auth.uid()
    OR status IN ('peer_verified', 'admin_verified')
    OR public.is_admin()
  );

DROP POLICY IF EXISTS "merchants can insert own prices" ON public.price_submissions;
CREATE POLICY "merchants can insert own prices"
  ON public.price_submissions
  FOR INSERT
  TO authenticated
  WITH CHECK (
    merchant_id = auth.uid()
    OR public.is_admin()
  );

DROP POLICY IF EXISTS "merchants can update own prices" ON public.price_submissions;
CREATE POLICY "merchants can update own prices"
  ON public.price_submissions
  FOR UPDATE
  TO authenticated
  USING (merchant_id = auth.uid() OR public.is_admin())
  WITH CHECK (merchant_id = auth.uid() OR public.is_admin());

-- Peer verifications
DROP POLICY IF EXISTS "users can read peer verifications" ON public.peer_verifications;
CREATE POLICY "users can read peer verifications"
  ON public.peer_verifications
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "users can create own peer verifications" ON public.peer_verifications;
CREATE POLICY "users can create own peer verifications"
  ON public.peer_verifications
  FOR INSERT
  TO authenticated
  WITH CHECK (verifier_id = auth.uid() OR public.is_admin());

-- Listings
DROP POLICY IF EXISTS "authenticated users can read active listings" ON public.listings;
CREATE POLICY "authenticated users can read active listings"
  ON public.listings
  FOR SELECT
  TO authenticated
  USING (
    status = 'active'
    OR merchant_id = auth.uid()
    OR public.is_admin()
  );

DROP POLICY IF EXISTS "merchants can manage own listings" ON public.listings;
CREATE POLICY "merchants can manage own listings"
  ON public.listings
  FOR ALL
  TO authenticated
  USING (merchant_id = auth.uid() OR public.is_admin())
  WITH CHECK (merchant_id = auth.uid() OR public.is_admin());

-- Audit log
DROP POLICY IF EXISTS "admins can read audit log" ON public.audit_log;
CREATE POLICY "admins can read audit log"
  ON public.audit_log
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "admins can insert audit log" ON public.audit_log;
CREATE POLICY "admins can insert audit log"
  ON public.audit_log
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

-- Emergencies
DROP POLICY IF EXISTS "authenticated users can read emergencies" ON public.emergencies;
CREATE POLICY "authenticated users can read emergencies"
  ON public.emergencies
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "admins can manage emergencies" ON public.emergencies;
CREATE POLICY "admins can manage emergencies"
  ON public.emergencies
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Notifications
DROP POLICY IF EXISTS "users can read own notifications" ON public.notifications;
CREATE POLICY "users can read own notifications"
  ON public.notifications
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "users can update own notifications" ON public.notifications;
CREATE POLICY "users can update own notifications"
  ON public.notifications
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() OR public.is_admin())
  WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "admins can insert notifications" ON public.notifications;
CREATE POLICY "admins can insert notifications"
  ON public.notifications
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin() OR user_id = auth.uid());

-- -----------------------------------------------------------------------------
-- Seed data
-- -----------------------------------------------------------------------------

INSERT INTO public.regions (id, name_mm) VALUES
  (1, 'မန္တလေးတိုင်းဒေသကြီး'),
  (2, 'စစ်ကိုင်းတိုင်းဒေသကြီး'),
  (3, 'မကွေးတိုင်းဒေသကြီး'),
  (4, 'ရှမ်းပြည်နယ်'),
  (5, 'ရန်ကုန်တိုင်းဒေသကြီး')
ON CONFLICT DO NOTHING;

INSERT INTO public.categories (id, name_mm) VALUES
  (1, 'ဆီထွက်သီးနှံ'),
  (2, 'စပါး'),
  (3, 'ပဲအမျိုးမျိုး')
ON CONFLICT DO NOTHING;

INSERT INTO public.products (id, name_mm, category_id) VALUES
  (1, 'နှမ်း', 1),
  (2, 'မြေပဲ', 1),
  (3, 'နေကြာ', 1),
  (4, 'မတ်ပဲ', 3),
  (5, 'ရွှေဘိုပေါ်ဆန်း', 2)
ON CONFLICT DO NOTHING;

INSERT INTO public.markets (id, name_mm, region_id) VALUES
  (1, 'မန္တလေးပွဲရုံ', 1),
  (2, 'မိတ္ထီလာပွဲရုံ', 1),
  (3, 'မကွေးကုန်စည်ဒိုင်', 3),
  (4, 'အောင်ပန်းဈေး', 4)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.regions', 'id'), COALESCE((SELECT MAX(id) FROM public.regions), 1), true);
SELECT setval(pg_get_serial_sequence('public.categories', 'id'), COALESCE((SELECT MAX(id) FROM public.categories), 1), true);
SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT MAX(id) FROM public.products), 1), true);
SELECT setval(pg_get_serial_sequence('public.markets', 'id'), COALESCE((SELECT MAX(id) FROM public.markets), 1), true);
